### ISSUE TITLE
Bring in IxState from Hyper?

### ISSUE THREAD

**Issue by owickstrom** [garyb/purescript-indexed-monad#7]
https://github.com/owickstrom/hyper/blob/master/src/Hyper/Middleware.purs#L9 is really an indexed state monad. Should we bring this into this library?

**Comment by garyb** [comment]
Maybe hold off for now? It's the indexed state transformer, and since I don't know how to fix the problem with transformers you raised elsewhere still, it's perhaps not worth adding something that might have to change later... having said that, I'm going to spend some time trying out Conor McBride's approach tonight, so it might all look a bit different if I can get that to work :smile:

**Comment by owickstrom** [comment]
We can close this, as you seem to have something coming up with the transformers.
